SELECT * FROM alunos;

SELECT TOP(3) PERCENT * FROM alunos;


-- PARA PAGINACAO --
SELECT * FROM alunos ORDER BY id
OFFSET 2 ROWS -- PULAR AS DUAS PRIMEIRAS LINHAS
FETCH FIRST 2 ROWS ONLY -- PEGAR OS 2 PROXIMOS REGISTROS